# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlatFinder
                                 A QGIS plugin
 This plugin seeks to help when searching for an appartment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-23
        copyright            : (C) 2024 by Kononow Stephan, Palka Nikolaus, Seisenbacher Daniel
        email                : a12002194@unet.univie.ac.at
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FlatFinder class from file FlatFinder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .FlatFinder import FlatFinder
    return FlatFinder(iface)
